name: foodtain_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter_slidable: ^1.2.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.3
  intl: ^0.18.0
  date_picker_timeline: ^1.2.5
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_local_notifications: ^16.3.0
  flutter_timezone: ^1.0.8
  timezone: ^0.9.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - lib/images/

